[package]
name = "vertex_attribute_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.37"
syn = "2.0.79"
wgpu = "22.0"
internals = { path = "../internals" }